version: "3"
services:
  practice_docker: 
    image: mmerdanovic/rimacgitapi
    ports: 
      - 49801:3000
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; npm start'
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:1docker2pass3@db:5432/rimacapidb
      - PORT=3000   
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1docker2pass3
      - POSTGRES_DB=rimacapidb